### ISSUE TITLE
Doesn't work on 1.19.4

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [Camotoy/BedrockSkinUtility#14]
MC Version 1.19.4
Fabric 0.14.9
MC Server   Paper 1.19.4 
Full logs: https://pb.superhub.xyz/VORWbb?fmt=raw

Error:
`[18:57:11] [Render thread/INFO]: Connecting to node1.novadev.ru, 25568
[18:57:14] [Render thread/INFO]: Started 6 worker threads
[18:57:15] [Render thread/INFO]: [CHAT] SPAWNRYS присоединился к игре
[18:57:16] [Render thread/INFO]: Loaded 9 advancements
[18:57:16] [Render thread/INFO]: [CHAT] You have been logged in automatically!
[18:57:16] [Render thread/INFO]: Stopping worker threads
[18:57:16] [Render thread/INFO]: Started 6 worker threads
[18:57:16] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.tropical_fish.ambient
[18:57:26] [Render thread/INFO]: [CHAT] Установлено время: 1000
[18:57:36] [Render thread/INFO]: [CHAT] be.SPAWNRYS5907 присоединился к игре
[18:57:36] [Netty Client IO #5/INFO]: Plugin message received from server!
[18:57:36] [Netty Client IO #5/ERROR]: Encountered exception while handling in channel with name "bedrockskin:data"
java.lang.NoSuchMethodError: 'int net.minecraft.class_1011.method_24031(int, int, int, int)'
	at net.camotoy.bedrockskinutility.client.pluginmessage.Decoder.toNativeImage(Decoder.java:42) ~[BedrockSkinUtility-1.4.0.jar:?]
	at net.camotoy.bedrockskinutility.client.pluginmessage.CapeDecoder.decode(CapeDecoder.java:42) ~[BedrockSkinUtility-1.4.0.jar:?]
	at net.camotoy.bedrockskinutility.client.pluginmessage.GeyserSkinManagerListener.receive(GeyserSkinManagerListener.java:44) ~[BedrockSkinUtility-1.4.0.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.3.0+a6f3ccfaf4-c29c18069cda2b62.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.0+a6f3ccfaf4-c29c18069cda2b62.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.0+a6f3ccfaf4-c29c18069cda2b62.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:90) ~[fabric-networking-api-v1-1.3.0+a6f3ccfaf4-c29c18069cda2b62.jar:?]
	at net.minecraft.class_634.handler$zmm000$fabric-networking-api-v1$handleCustomPayload(class_634.java:3241) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:155) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[viafabricplus-2.5.5.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[viafabricplus-2.5.5.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:57:36] [Render thread/INFO]: Stopping worker threads
[18:57:36] [Render thread/INFO]: emissive suffixes loaded: {_e}`

**Comment by Camotoy** [comment]
Please use version 1.5.0. Thanks.
